name: Build Dylib

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger build for pull requests

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Xcode Command Line Tools
      - name: Install Xcode Command Line Tools
        run: |
          xcode-select --install
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      # Step 3: (Optional) Install additional dependencies (like ldid)
      - name: Install Dependencies
        run: |
          brew install ldid

      # Step 4: Run make to build the dylib
      - name: Build dylib
        run: |
          make

      # Step 5: Upload the built dylib as an artifact
      - name: Upload dylib artifact
        uses: actions/upload-artifact@v3
        with:
          name: libinject.dylib
          path: libinject.dylib
