name: Build Tweak (dylib) with Theos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Theos environment
      run: |
        sudo apt update
        sudo apt install -y git
        sudo apt install -y libtool
        sudo apt install -y autoconf
        sudo apt install -y curl
        sudo apt install -y clang
        sudo apt install -y make
        # Install Theos
        git clone https://github.com/theos/theos.git ~/theos
        echo "export THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "export PATH=\$THEOS/bin:\$PATH" >> $GITHUB_ENV

    - name: Automatically detect and build tweak
      run: |
        # Find the directory that contains the tweak.xm file (case-insensitive search)
        TWEAK_DIR=$(find . -type f -iname "tweak.xm" -exec dirname {} \; | head -n 1)
        if [ -z "$TWEAK_DIR" ]; then
          echo "No tweak.xm file found, exiting."
          exit 1
        fi

        echo "Building tweak in directory: $TWEAK_DIR"
        
        # Change to the detected tweak directory
        cd $TWEAK_DIR

        # Automatically find the Makefile (case-insensitive search)
        MAKEFILE=$(find . -type f -iname "Makefile" | head -n 1)
        if [ -z "$MAKEFILE" ]; then
          echo "No Makefile found in $TWEAK_DIR, exiting."
          exit 1
        fi

        echo "Using Makefile: $MAKEFILE"
        
        # Check if the Makefile contains a valid TWEAK_NAME target
        if ! grep -q "TWEAK_NAME" "$MAKEFILE"; then
          echo "No valid target (TWEAK_NAME) found in Makefile, exiting."
          exit 1
        fi

        # Run the build
        make clean || true  # Allow make clean to fail without stopping the process
        make

    - name: Upload dylib as artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-dylib
        path: $TWEAK_DIR/.theos/obj/iphone/debug/arm64/libTweak.dylib  # Adjust path if necessary
