name: Build and Deploy Dylib

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Dylib with Theos
    runs-on: macos-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Theos and dependencies
      - name: Install Theos
        run: |
          echo "Installing Theos..."
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> $GITHUB_ENV
          export THEOS=~/theos
          echo "Theos installed at: $THEOS"
          brew install ldid

      # Step 3: Build the dylib
      - name: Build with Theos
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make clean
          make package FINALPACKAGE=1

      # Step 4: Upload the .dylib as an artifact
      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BuiltDylib
          path: .theos/obj/*.dylib
