name: Auto Build and Upload dylib

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Theos
        run: |
          # Clone Theos repository
          git clone --recursive https://github.com/theos/theos.git /tmp/theos
          export THEOS=/tmp/theos
          export PATH=$THEOS/bin:$PATH
          brew install ldid

      - name: Find Makefile and .xm files
        id: find_files
        run: |
          # Find the Makefile and tweak.xm files
          MAKEFILE_PATH=$(find . -name "Makefile" | head -n 1)
          if [ -z "$MAKEFILE_PATH" ]; then
            echo "No Makefile found. Exiting..."
            exit 1
          fi
          echo "Makefile found at $MAKEFILE_PATH"
          echo "MAKEFILE_PATH=$MAKEFILE_PATH" >> $GITHUB_ENV

          XM_FILE_PATH=$(find . -name "*.xm" | head -n 1)
          if [ -z "$XM_FILE_PATH" ]; then
            echo "No .xm file found. Exiting..."
            exit 1
          fi
          echo "Tweak source found at $XM_FILE_PATH"
          echo "XM_FILE_PATH=$XM_FILE_PATH" >> $GITHUB_ENV

      - name: Build dylib
        run: |
          echo "Building dylib using Makefile at $MAKEFILE_PATH"
          cd $(dirname $MAKEFILE_PATH)

          # Set the THEOS directory for the build
          export THEOS=/tmp/theos

          # Run the make command
          make

      - name: Find and upload dylib artifact
        id: find_and_upload
        run: |
          # Find the built .dylib file
          DYLIB_FILE=$(find $(dirname $MAKEFILE_PATH) -name "*.dylib" | head -n 1)
          if [ -z "$DYLIB_FILE" ]; then
            echo "No .dylib file found. Exiting..."
            exit 1
          fi
          echo "Dylib found at: $DYLIB_FILE"
          echo "DYLIB_FILE=$DYLIB_FILE" >> $GITHUB_ENV

      - name: Upload dylib artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-dylib
          path: ${{ env.DYLIB_FILE }}
